[phases.setup]
nixPkgs = [
  "gdal",
  "python311",
  "postgresql",
  "libgeos"
]

[phases.build]
cmds = [
  "cd backend",
  "python -m pip install -r requirements.txt"
]

[start]
cmd = "cd backend && gunicorn backend.wsgi:application"