@echo off
echo Running makemigrations...
python manage.py makemigrations

echo Running migrations...
python manage.py migrate

echo Loading users fixture...
python manage.py loaddata users_fixture.json

echo Loading posts fixture...
python manage.py loaddata posts_fixture.json

echo Loading post's images fixture...
python manage.py loaddata postImages_fixture.json

echo Loading comments fixture...
python manage.py loaddata comments_fixture.json

echo Loading likes fixture...
python manage.py loaddata likes_fixture.json

echo Starting the development server...
python manage.py runserver
pause
