[build]
builder = "nixpacks"
buildCommand = "cd backend && pip install -r requirements.txt"

[deploy]
startCommand = "cd backend && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn backend.wsgi:application"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10